In [2]:
import numpy as np
 

In [4]:
arr1 = np.array([1,2,3])
arr2 = np.array([[1,2,3],[4,5,6]])


## increase dimention and squeeze command

In [17]:
arr1_inc_dim = np.expand_dims(arr1,axis=0)
print(arr1_inc_dim.shape)
arr1_sque = np.squeeze(arr1_inc_dim )
print(arr1_sque.shape)

(1, 3)
(3,)


# Repeat and tiling function 

In [18]:
arr1_repe = np.repeat(arr1 , 2)
print(arr1_repe)
arr1_tile = np.tile(arr1,2)
print(arr1_tile)

[1 1 2 2 3 3]
[1 2 3 1 2 3]


## Unfuncs

In [5]:
addi = np.add(arr1,arr2) #we can directly add arrays
print(addi)

[[2 4 6]
 [5 7 9]]


### reduce accumulate outer

In [17]:
print(np.add.reduce(np.arange(5)))
print(np.add.accumulate(np.arange(5)))
print(np.multiply.outer([1,2,3],[4,5]))

10
[ 0  1  3  6 10]
[[ 4  5]
 [ 8 10]
 [12 15]]


In [49]:

arr1_at = np.subtract.at(arr1,2,10)
print(arr1)

[1 2 3]


In [ ]:
arr2_unsort = np.array([[1,3,2],[6,4,5]])
print(arr2_unsort)
arr2_sorted = np.sort(arr2_unsort)
print (arr2_sorted)

[[1 3 2]
 [6 4 5]]
[[1 2 3]
 [4 5 6]]


In [64]:
arr2_ndsort = arr2_unsort
print(arr2_ndsort)
np.ndarray.sort(arr2_ndsort)
print(arr2_ndsort)

[[1 3 2]
 [6 4 5]]
[[1 2 3]
 [4 5 6]]


In [66]:
dt = np.dtype([('name','U10'),('age',int)])
x = np.array([("Akash",22),("dev",20)],dtype=dt)
x_sort = np.sort(x , order='age')
print(x_sort)

[('dev', 20) ('Akash', 22)]


In [78]:
print(arr1)
print(np.searchsorted(arr1 , 4))

[1 2 3]
3


There are quite a few operations that can be done on 1d arrays 
I'll just write them down 


In [ ]:
# np.unique() -> finds unique elements
# np.union1d() -> union of two 1d array
# np.intersect1d() -> intersection of two 1d array
# np.setdiff1d() -> find elements that are present in one but not in other
# np.setxor1d -> Xor (or symmetric difference) of two 1d array

### Structured arrays 

In [83]:
dt = np.dtype([('name','U10'),('age',int)])
struc_arr = np.array([("Akash",22),("dev",20),("dameon",19)],dtype=dt)

#Fancy indexing
teen = struc_arr[struc_arr['age']<20]
print(teen)

# idk ill think of something -- changing a variable that borrows data from an array also changes the original array 
namee = struc_arr["name"]
namee[2] = "nissin"
print(struc_arr)

#searching -- we already done this
teen_index = np.where(struc_arr["age"]<20)
print(struc_arr[teen_index])


[('dameon', 19)]
[('Akash', 22) ('dev', 20) ('nissin', 19)]
[('nissin', 19)]


In [ ]:
from numpy.random import *
rng = default_rng()


#generating random number

print("legacy method:")
np.random.rand(3,2)



legacy method:


array([[0.22591492, 0.73060086],
       [0.59551353, 0.23559575],
       [0.65727591, 0.05945846]])

In [130]:
print("new api:")
rng.uniform(0.0 , 1.0 ,size=None)

new api:


0.1689749165466049

# INITIAL DONE 