In [2]:
import numpy as np
 

In [4]:
arr1 = np.array([1,2,3])
arr2 = np.array([[1,2,3],[4,5,6]])


## increase dimention and squeeze command

In [17]:
arr1_inc_dim = np.expand_dims(arr1,axis=0)
print(arr1_inc_dim.shape)
arr1_sque = np.squeeze(arr1_inc_dim )
print(arr1_sque.shape)

(1, 3)
(3,)


# Repeat and tiling function 

In [18]:
arr1_repe = np.repeat(arr1 , 2)
print(arr1_repe)
arr1_tile = np.tile(arr1,2)
print(arr1_tile)

[1 1 2 2 3 3]
[1 2 3 1 2 3]


## Unfuncs

In [5]:
addi = np.add(arr1,arr2) #we can directly add arrays
print(addi)

[[2 4 6]
 [5 7 9]]


### reduce accumulate outer

In [ ]:
print(np.add.reduce(np.arange(5)))
print(np.add.accumulate(np.arange(5)))
print(np.multiply.outer([1,2,3],[4,5]))

10
[ 0  1  3  6 10]
